name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup EAS CLI
        run: npm install -g eas-cli@latest

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Standalone Preview APK
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EAS_BUILD_SKIP_LOCKFILE_CHECK: "1"
        run: |
          npx eas-cli project:init --id 7dcbd778-af48-4b2f-b40a-f2497692dd90 --force
          eas build -p android --profile preview --non-interactive --no-wait
